version: 0.1.{build}
configuration:
- Debug
- Release
platform: Win32
build:
  project: Sparky.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - y@nchernikov.com
  subject: Sparky CI Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true